"""
Versioned Schedule Catalog System for VaxAssist AI.
Contains clearly labeled DEMO schedule guidelines for development.
NOTE: Pure deterministic rule dataset — no LLM calculation or generated medical advice.
"""

from typing import List, Dict, Any, Optional

SCHEDULE_VERSION = "v1.0.0-demo-2026"
EFFECTIVE_DATE = "2024-01-01"
DEFAULT_SOURCE = "DEMO - Universal Immunization Program (UIP) & WHO Essential Guidelines (v1.0.0-demo-2026)"

# Versioned Rule Definition
# recommended_age_days: Approximate days from birth when vaccine is recommended
# overdue_grace_days: Days after recommended age after which the dose is considered overdue if not administered
DEMO_SCHEDULE_RULES: List[Dict[str, Any]] = [
    # --- Birth ---
    {
        "rule_id": "UIP-BCG-0",
        "country": "IN",
        "region": "National",
        "vaccine": "BCG",
        "vaccine_display_name": "BCG (Tuberculosis)",
        "dose": "Birth Dose",
        "recommended_age_label": "At Birth",
        "min_age_days": 0,
        "recommended_age_days": 0,
        "overdue_grace_days": 28,  # Overdue if not given within 28 days of birth
        "interval_days": 0,
        "eligibility_conditions": {"max_age_days": 365},
        "description": "Protects against childhood tuberculosis and tuberculous meningitis.",
        "source": DEFAULT_SOURCE,
        "schedule_version": SCHEDULE_VERSION,
        "effective_date": EFFECTIVE_DATE,
    },
    {
        "rule_id": "UIP-HEPB-0",
        "country": "IN",
        "region": "National",
        "vaccine": "Hepatitis B",
        "vaccine_display_name": "Hepatitis B (Birth Dose)",
        "dose": "Birth Dose",
        "recommended_age_label": "At Birth (within 24 hrs)",
        "min_age_days": 0,
        "recommended_age_days": 0,
        "overdue_grace_days": 14,
        "interval_days": 0,
        "eligibility_conditions": {"max_age_days": 30},
        "description": "Birth dose to prevent perinatal transmission of Hepatitis B virus.",
        "source": DEFAULT_SOURCE,
        "schedule_version": SCHEDULE_VERSION,
        "effective_date": EFFECTIVE_DATE,
    },
    {
        "rule_id": "UIP-OPV-0",
        "country": "IN",
        "region": "National",
        "vaccine": "Polio (OPV / IPV)",
        "vaccine_display_name": "Oral Polio Vaccine (OPV 0)",
        "dose": "Birth Dose",
        "recommended_age_label": "At Birth (within 15 days)",
        "min_age_days": 0,
        "recommended_age_days": 0,
        "overdue_grace_days": 21,
        "interval_days": 0,
        "eligibility_conditions": {"max_age_days": 30},
        "description": "Zero dose Oral Polio Vaccine given at birth.",
        "source": DEFAULT_SOURCE,
        "schedule_version": SCHEDULE_VERSION,
        "effective_date": EFFECTIVE_DATE,
    },

    # --- 6 Weeks (42 Days) ---
    {
        "rule_id": "UIP-DTP-1",
        "country": "IN",
        "region": "National",
        "vaccine": "Tdap / DTP (Diphtheria, Tetanus, Pertussis)",
        "vaccine_display_name": "Pentavalent / DTP (Dose 1)",
        "dose": "Dose 1",
        "recommended_age_label": "6 Weeks",
        "min_age_days": 42,
        "recommended_age_days": 42,
        "overdue_grace_days": 21,
        "interval_days": 0,
        "eligibility_conditions": {},
        "description": "First dose of DTP-containing primary series.",
        "source": DEFAULT_SOURCE,
        "schedule_version": SCHEDULE_VERSION,
        "effective_date": EFFECTIVE_DATE,
    },
    {
        "rule_id": "UIP-OPV-1",
        "country": "IN",
        "region": "National",
        "vaccine": "Polio (OPV / IPV)",
        "vaccine_display_name": "Oral Polio Vaccine (OPV 1)",
        "dose": "Dose 1",
        "recommended_age_label": "6 Weeks",
        "min_age_days": 42,
        "recommended_age_days": 42,
        "overdue_grace_days": 21,
        "interval_days": 28,
        "eligibility_conditions": {},
        "description": "First primary dose of Oral Polio Vaccine.",
        "source": DEFAULT_SOURCE,
        "schedule_version": SCHEDULE_VERSION,
        "effective_date": EFFECTIVE_DATE,
    },
    {
        "rule_id": "UIP-ROTA-1",
        "country": "IN",
        "region": "National",
        "vaccine": "Rotavirus",
        "vaccine_display_name": "Rotavirus (Dose 1)",
        "dose": "Dose 1",
        "recommended_age_label": "6 Weeks",
        "min_age_days": 42,
        "recommended_age_days": 42,
        "overdue_grace_days": 21,
        "interval_days": 0,
        "eligibility_conditions": {"max_age_days": 240},
        "description": "Oral rotavirus drops to protect against severe diarrhea.",
        "source": DEFAULT_SOURCE,
        "schedule_version": SCHEDULE_VERSION,
        "effective_date": EFFECTIVE_DATE,
    },

    # --- 10 Weeks (70 Days) ---
    {
        "rule_id": "UIP-DTP-2",
        "country": "IN",
        "region": "National",
        "vaccine": "Tdap / DTP (Diphtheria, Tetanus, Pertussis)",
        "vaccine_display_name": "Pentavalent / DTP (Dose 2)",
        "dose": "Dose 2",
        "recommended_age_label": "10 Weeks",
        "min_age_days": 70,
        "recommended_age_days": 70,
        "overdue_grace_days": 21,
        "interval_days": 28,  # Minimum 4 weeks from Dose 1
        "prerequisite_rule_id": "UIP-DTP-1",
        "eligibility_conditions": {},
        "description": "Second dose of DTP-containing primary series.",
        "source": DEFAULT_SOURCE,
        "schedule_version": SCHEDULE_VERSION,
        "effective_date": EFFECTIVE_DATE,
    },
    {
        "rule_id": "UIP-OPV-2",
        "country": "IN",
        "region": "National",
        "vaccine": "Polio (OPV / IPV)",
        "vaccine_display_name": "Oral Polio Vaccine (OPV 2)",
        "dose": "Dose 2",
        "recommended_age_label": "10 Weeks",
        "min_age_days": 70,
        "recommended_age_days": 70,
        "overdue_grace_days": 21,
        "interval_days": 28,
        "prerequisite_rule_id": "UIP-OPV-1",
        "eligibility_conditions": {},
        "description": "Second primary dose of Oral Polio Vaccine.",
        "source": DEFAULT_SOURCE,
        "schedule_version": SCHEDULE_VERSION,
        "effective_date": EFFECTIVE_DATE,
    },

    # --- 14 Weeks (98 Days) ---
    {
        "rule_id": "UIP-DTP-3",
        "country": "IN",
        "region": "National",
        "vaccine": "Tdap / DTP (Diphtheria, Tetanus, Pertussis)",
        "vaccine_display_name": "Pentavalent / DTP (Dose 3)",
        "dose": "Dose 3",
        "recommended_age_label": "14 Weeks",
        "min_age_days": 98,
        "recommended_age_days": 98,
        "overdue_grace_days": 21,
        "interval_days": 28,
        "prerequisite_rule_id": "UIP-DTP-2",
        "eligibility_conditions": {},
        "description": "Third primary dose completing the infant DTP series.",
        "source": DEFAULT_SOURCE,
        "schedule_version": SCHEDULE_VERSION,
        "effective_date": EFFECTIVE_DATE,
    },

    # --- 9-12 Months (270 Days) ---
    {
        "rule_id": "UIP-MMR-1",
        "country": "IN",
        "region": "National",
        "vaccine": "MMR (Measles, Mumps, Rubella)",
        "vaccine_display_name": "MR / MMR (Dose 1)",
        "dose": "Dose 1",
        "recommended_age_label": "9 Months",
        "min_age_days": 270,
        "recommended_age_days": 270,
        "overdue_grace_days": 60,
        "interval_days": 0,
        "eligibility_conditions": {},
        "description": "First dose of Measles-Rubella / MMR vaccine.",
        "source": DEFAULT_SOURCE,
        "schedule_version": SCHEDULE_VERSION,
        "effective_date": EFFECTIVE_DATE,
    },

    # --- 16-24 Months (480 Days) ---
    {
        "rule_id": "UIP-MMR-2",
        "country": "IN",
        "region": "National",
        "vaccine": "MMR (Measles, Mumps, Rubella)",
        "vaccine_display_name": "MR / MMR (Dose 2)",
        "dose": "Dose 2",
        "recommended_age_label": "16-24 Months",
        "min_age_days": 480,
        "recommended_age_days": 480,
        "overdue_grace_days": 90,
        "interval_days": 180,
        "prerequisite_rule_id": "UIP-MMR-1",
        "eligibility_conditions": {},
        "description": "Second dose of Measles-Rubella / MMR booster.",
        "source": DEFAULT_SOURCE,
        "schedule_version": SCHEDULE_VERSION,
        "effective_date": EFFECTIVE_DATE,
    },
    {
        "rule_id": "UIP-DTP-B1",
        "country": "IN",
        "region": "National",
        "vaccine": "Tdap / DTP (Diphtheria, Tetanus, Pertussis)",
        "vaccine_display_name": "DTP Booster 1",
        "dose": "Booster 1",
        "recommended_age_label": "16-24 Months",
        "min_age_days": 480,
        "recommended_age_days": 480,
        "overdue_grace_days": 90,
        "interval_days": 180,
        "prerequisite_rule_id": "UIP-DTP-3",
        "eligibility_conditions": {},
        "description": "First childhood booster dose of DTP vaccine.",
        "source": DEFAULT_SOURCE,
        "schedule_version": SCHEDULE_VERSION,
        "effective_date": EFFECTIVE_DATE,
    },

    # --- 5-6 Years (1825 Days) ---
    {
        "rule_id": "UIP-DTP-B2",
        "country": "IN",
        "region": "National",
        "vaccine": "Tdap / DTP (Diphtheria, Tetanus, Pertussis)",
        "vaccine_display_name": "DTP Booster 2",
        "dose": "Booster 2",
        "recommended_age_label": "5-6 Years",
        "min_age_days": 1825,
        "recommended_age_days": 1825,
        "overdue_grace_days": 180,
        "interval_days": 365,
        "prerequisite_rule_id": "UIP-DTP-B1",
        "eligibility_conditions": {},
        "description": "Second childhood booster dose of DTP vaccine before school entry.",
        "source": DEFAULT_SOURCE,
        "schedule_version": SCHEDULE_VERSION,
        "effective_date": EFFECTIVE_DATE,
    },

    # --- 10 Years & 16 Years (Td Booster) ---
    {
        "rule_id": "UIP-TD-10Y",
        "country": "IN",
        "region": "National",
        "vaccine": "Tdap / DTP (Diphtheria, Tetanus, Pertussis)",
        "vaccine_display_name": "Tetanus & adult Diphtheria (Td 10 Yrs)",
        "dose": "Booster",
        "recommended_age_label": "10 Years",
        "min_age_days": 3650,
        "recommended_age_days": 3650,
        "overdue_grace_days": 365,
        "interval_days": 0,
        "eligibility_conditions": {},
        "description": "Adolescent Td booster for long-term tetanus & diphtheria protection.",
        "source": DEFAULT_SOURCE,
        "schedule_version": SCHEDULE_VERSION,
        "effective_date": EFFECTIVE_DATE,
    },

    # --- Annual Influenza (Recommended for all ages) ---
    {
        "rule_id": "WHO-FLU-ANNUAL",
        "country": "GLOBAL",
        "region": "All",
        "vaccine": "Influenza (Quadrivalent Flu Shot)",
        "vaccine_display_name": "Annual Influenza Shot",
        "dose": "Annual Dose",
        "recommended_age_label": "Annual (6+ months)",
        "min_age_days": 180,
        "recommended_age_days": 180,
        "overdue_grace_days": 365,
        "interval_days": 300,
        "eligibility_conditions": {},
        "description": "Seasonal quadrivalent influenza vaccination recommended annually.",
        "source": DEFAULT_SOURCE,
        "schedule_version": SCHEDULE_VERSION,
        "effective_date": EFFECTIVE_DATE,
    },

    # --- COVID-19 Primary & Booster Series ---
    {
        "rule_id": "WHO-COVID-1",
        "country": "GLOBAL",
        "region": "All",
        "vaccine": "COVID-19",
        "vaccine_display_name": "COVID-19 (Primary Dose 1)",
        "dose": "Dose 1",
        "recommended_age_label": "Eligible from 6 Months / 12 Years",
        "min_age_days": 180,
        "recommended_age_days": 180,
        "overdue_grace_days": 180,
        "interval_days": 0,
        "eligibility_conditions": {},
        "description": "Initial primary series dose for COVID-19 immunization.",
        "source": DEFAULT_SOURCE,
        "schedule_version": SCHEDULE_VERSION,
        "effective_date": EFFECTIVE_DATE,
    },
    {
        "rule_id": "WHO-COVID-2",
        "country": "GLOBAL",
        "region": "All",
        "vaccine": "COVID-19",
        "vaccine_display_name": "COVID-19 (Primary Dose 2)",
        "dose": "Dose 2",
        "recommended_age_label": "4-8 Weeks after Dose 1",
        "min_age_days": 208,
        "recommended_age_days": 208,
        "overdue_grace_days": 90,
        "interval_days": 28,
        "prerequisite_rule_id": "WHO-COVID-1",
        "eligibility_conditions": {},
        "description": "Second dose completing primary COVID-19 series.",
        "source": DEFAULT_SOURCE,
        "schedule_version": SCHEDULE_VERSION,
        "effective_date": EFFECTIVE_DATE,
    },
]


def get_schedule_catalog(
    country: Optional[str] = None,
    region: Optional[str] = None,
    version: Optional[str] = None
) -> List[Dict[str, Any]]:
    """Retrieve filtered schedule rules from the versioned catalog."""
    rules = DEMO_SCHEDULE_RULES
    if country and country != "ALL":
        rules = [r for r in rules if r["country"] in [country, "GLOBAL"]]
    if region and region != "ALL":
        rules = [r for r in rules if r["region"] in [region, "All", "National"]]
    if version:
        rules = [r for r in rules if r["schedule_version"] == version]
    return rules
